config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'subjects#index'

  resources :classes, controller: :subjects, as: :subjects, only: [] do
    resources :professors, only: :index
  end

  resources :professors, only: :show
  resources :reviews, only: [:create, :update, :destroy]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/professor.rb
class Professor < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name,  presence: true

  has_and_belongs_to_many :subjects
  has_many :reviews, dependent: :destroy

  scope :include_overall_rating_summary, -> do
    left_outer_joins(:reviews).
    select('professors.*, avg(reviews.rating) as average_rating, count(reviews.id) as reviews_count').
    group('professors.id')
  end

  accepts_nested_attributes_for :subjects, allow_destroy: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/professor_subject_reviews_summary.rb
class ProfessorSubjectReviewsSummary < ApplicationRecord

  scope :on_subject, ->(subject){where(subject_id: subject)}

  def readonly?
    true
  end
end

app/models/review.rb
class Review < ApplicationRecord

  VALID_RATINGS = 1..5

  belongs_to :user
  belongs_to :professor
  belongs_to :subject

  validates :user_id, uniqueness: {scope: [:professor_id, :subject_id]}
  validates :rating,  inclusion: {in: VALID_RATINGS}
end

app/models/subject.rb
class Subject < ApplicationRecord
  self.per_page = 15

  validates :code, uniqueness: true, presence: true

  has_and_belongs_to_many :professors
  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name,  presence: true

  has_many :reviews, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  def index
    @professors_index = ProfessorsIndexFacade.new(current_user,
                                                  params[:subject_id],
                                                  params[:page])

    respond_to do |format|
      format.html
      format.json do
        render :index, locals: {professors_index: @professors_index}
      end
    end
  end

  def show
    @professor = ProfessorShowFacade.new(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_facade, except: :create

  def create
    review = current_user.reviews.create(create_review_params)
    @reviews_facade = ReviewsFacade.new(current_user, review.id)

    respond_to do |format|
      format.json { render :show }
    end
  end

  def update
    @reviews_facade.review.update(review_params)

    respond_to do |format|
      format.json { render :show }
    end
  end

  def destroy
    @reviews_facade.review.destroy

    respond_to do |format|
      format.json { render :show }
    end
  end

  private

  def set_facade
    @reviews_facade = ReviewsFacade.new(current_user, params[:id])
  end

  def create_review_params
    params.require(:review).permit(:professor_id, :subject_id, :rating, :description)
  end

  def review_params
    params.require(:review).permit(:rating, :description)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects = SubjectsIndexFacade.new(params[:page], params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flashes.html.slim
- map = {'alert' => 'info', 'notice' => 'success'}
- flash.each do |key, content|
  .flash class="alert alert-#{map[key]}"
    a href='#' class='close' data-dismiss='alert' aria-label='close' &times;
    = content

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prof Review</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class='navbar navbar-default navbar-fixed-top'>
      <div class='container'>
        <div class='navbar-header'>
          <a href='/' class='navbar-brand'>Prof Review</a>
          <button class='navbar-toggle' type='button' data-toggle='collapse' data-target='#navbar-main'>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
          </button>
        </div>

        <div id='navbar' class='navbar-collapse collapse'>
          <ul class='nav navbar-nav navbar-right'>
            <% if user_signed_in? %>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, data: {confirm: "Are you sure you want to logout?"}%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class='container'>
      <%= render partial: 'layouts/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/professors/_overall_summary.html.slim
.col-md-4.col-xs-12
  .panel.panel-primary
    .panel-heading
      h3.panel-title Overall Summary
    table.table.lead
      tr
        th Average Rating
        td
          span.badge.progress-bar-info
            - if @professor.average_rating
              = @professor.average_rating.round(1)
              = icon 'fas', 'star'
            -  else
              | n/a
      tr
        th Reviews count
        td
          span.badge.progress-bar-info
            = @professor.reviews_count

app/views/professors/_per_class_summary.html.slim
.col-md-8.col-xs-12
  .panel.panel-primary
    .panel-heading
      h3.panel-title Summary per class
    - if @professor.subjects.any?
      table.table
        thead
          tr
            th Class
            th.text-center Rating
            th.text-center Reviews count
        tbody
          - @professor.subjects.each do |subject|
            tr
              td= subject.code
              td.text-center= @professor.average_rating_on_subject(subject) || 'n/a'
              td.text-center= @professor.review_count_on_subject(subject) || '0'
    - else
      .panel-body= 'Professor has not classes yet'

app/views/professors/index.html.slim
.row
  .col-xs-12
    .small
      = link_to 'Classes', root_path
      | &nbsp;
      = icon('fas', 'angle-right')
      | &nbsp;
      = @professors_index.subject_code
    h1.page-header
      = icon('fas', 'graduation-cap fa-sm')
      span= 'Professors'

  .col-xs-12
    .professor-list-container data-professors='#{
      ApplicationController.new.
        render_to_string(
          template: "professors/index",
          formats: :json,
          locals: {professors_index: @professors_index})}'

app/views/professors/show.html.slim
.row
  .col-xs-12
    .small.pull-right
    .small
      = link_to 'Go back', :back
      | &nbsp;|&nbsp;
      | Professor's Profile
    h1.page-header
      = icon('fas', 'graduation-cap fa-sm')
      span= @professor.full_name
  = render "overall_summary"
  = render "per_class_summary"

app/views/subjects/_subject.html.slim
.subject-list-item.col-xs-12.col-sm-4
  a.subject-list-item__wrapper href="#{subject_professors_path(subject)}"
    h3= subject.code
    u.pull-right  See Professors →
    .clearfix

app/views/subjects/index.html.slim
.row
  .col-xs-12
    h1.page-header
      | Class List
      = search_form_for @subjects.q, url: root_path, class: 'form-inline pull-right' do |f|
        = f.search_field :code_cont, class: 'form-control', placeholder: 'Search class'
        | &nbsp;
        = button_tag class: 'btn btn-sm btn-primary' do
          = icon('fas', 'search')
  .col-xs-12
    - if @subjects.any?
      = render @subjects.all
      .pagination-container
        = will_paginate @subjects.all, renderer: BootstrapPagination::Rails
    - else
      p
        | Got no results.
        | &nbsp;
        a href='/' Show all classes